<?php

/**
 * custom credit card skin to use with PayTrace tokenized payments or one-time payments
 */
?>
<?php
function getStoredPayments($customer_id)
{
	$url = 'http://service.microk12.com/index.php/tkn/listItems';
	//$url = 'http://192.168.50.132/microk12-ci/index.php/tkn/listItems';
	$data = array('customerid'=>md5($customer_id));
	
	$options = array(
		'http' => array(
			'header'	=> "Content-type: application/x-www-form-urlencoded",
			'method'	=> 'POST',
			'content'	=> http_build_query($data),
		),
	);
	$context = stream_context_create($options);
	$result = file_get_contents($url, false, $context);
	
	return $result;
}

$_code = $this->getMethodCode();
$customer_data=Mage::getSingleton('customer/session')->getCustomer();
$customer_id = $customer_data->getEmail();
$payments = json_decode(getStoredPayments($customer_id));
?>

<div id="payment_form_<?php echo $_code; ?>">
	<select class="form-control input-select required-entry" id="<?php echo $_code ?>_cc_token" name="payment[cc_token]">
		<option value='manual'>Enter Manually</option>
		<?php foreach($payments as $token): ?>
		<option value="<?php echo $token->token_id; ?>"><?php echo $token->last4; ?> - <?php echo $token->expires; ?> - <?php echo $token->name; ?></option>
		<?php endforeach; ?>
	</select>
	<!-- TODO: add the manual entry form -->
</div>